import type { Usage } from "@earendil-works/pi-ai";

export type AgentUsage = {
  /** Tokens PUM sent to the model, including tokens written to a provider cache. */
  outgoing: number;
  /** Tokens generated by the model. Pi includes reported reasoning tokens here. */
  incoming: number;
  /** Prompt tokens served from a provider cache. */
  cacheRead: number;
  cost: number;
  contextPct: number | null;
};

export const emptyAgentUsage = (): AgentUsage => ({
  outgoing: 0,
  incoming: 0,
  cacheRead: 0,
  cost: 0,
  contextPct: null,
});

/** Convert retained pre-metric usage records without discarding their token total. */
export function normalizeAgentUsage(value: unknown): AgentUsage {
  if (!value || typeof value !== "object") return emptyAgentUsage();
  const usage = value as Record<string, unknown>;
  const cost = typeof usage.cost === "number" ? usage.cost : 0;
  const contextPct = typeof usage.contextPct === "number" ? usage.contextPct : null;
  if (
    typeof usage.outgoing === "number" ||
    typeof usage.incoming === "number" ||
    typeof usage.cacheRead === "number"
  ) {
    return {
      outgoing: typeof usage.outgoing === "number" ? usage.outgoing : 0,
      incoming: typeof usage.incoming === "number" ? usage.incoming : 0,
      cacheRead: typeof usage.cacheRead === "number" ? usage.cacheRead : 0,
      cost,
      contextPct,
    };
  }

  // Legacy records stored only totalTokens. The exact split is unavailable.
  // Keep the total visible as outgoing until a retained session can rebuild it.
  return {
    outgoing: typeof usage.tokens === "number" ? usage.tokens : 0,
    incoming: 0,
    cacheRead: 0,
    cost,
    contextPct,
  };
}

type TurnUsage = Partial<Omit<Usage, "cost">> & {
  cost?: Partial<Usage["cost"]>;
};

export function addTurnUsage(
  current: AgentUsage,
  usage: TurnUsage | undefined,
  contextWindow: number | undefined,
): AgentUsage {
  if (!usage) return current;
  const input = usage.input ?? 0;
  const output = usage.output ?? 0;
  const cacheRead = usage.cacheRead ?? 0;
  const cacheWrite = usage.cacheWrite ?? 0;
  const promptTokens = input + cacheRead + cacheWrite;
  return {
    outgoing: current.outgoing + input + cacheWrite,
    incoming: current.incoming + output,
    cacheRead: current.cacheRead + cacheRead,
    cost: current.cost + (usage.cost?.total ?? 0),
    contextPct: contextWindow
      ? Math.min(100, Math.round((promptTokens / contextWindow) * 100))
      : null,
  };
}

export function usageFromEntries(
  entries: readonly any[],
  contextWindow: number | undefined,
): AgentUsage {
  let result = emptyAgentUsage();
  for (const entry of entries) {
    const usage = entry?.type === "message" && entry.message?.role === "assistant"
      ? entry.message.usage
      : (entry?.type === "compaction" || entry?.type === "branch_summary")
        ? entry.usage
        : undefined;
    if (usage) result = addTurnUsage(result, usage, contextWindow);
  }
  return result;
}
