import type { SessionInfo } from "@earendil-works/pi-coding-agent";
import { createReadStream } from "node:fs";
import { readdir, stat, unlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { StringDecoder } from "node:string_decoder";

export type KnownSessionTokens = {
  /** Input tokens sent by PUM, including provider cache writes. */
  outgoing?: number;
  /** Output tokens generated by the model. */
  incoming?: number;
  /** Prompt tokens reused from a provider cache. */
  cacheRead?: number;
};

export type SessionHistoryMetadata = {
  /** Latest persisted user-message timestamp. Null means that no valid timestamp exists. */
  latestUserMessageAt: Date | null;
  /** Current on-disk JSONL file size in bytes. Null means that stat failed. */
  fileBytes: number | null;
  tokens: KnownSessionTokens;
};

export type SessionHistoryItem = SessionInfo & {
  historyMetadata: SessionHistoryMetadata;
};

type CacheEntry = {
  key: string;
  metadata: SessionHistoryMetadata;
};

/** Files written next to `<session>.jsonl` that live and die with it. */
/**
 * Sidecars a session owns. A suffix missing here leaks one file per deleted
 * session, so every new companion file must be added.
 */
export const COMPANION_SUFFIXES = [
  ".news.json",
  ".stats.json",
  ".tool-groups.json",
  ".goal.json",
  ".todo.json",
] as const;

const DEFAULT_MAX_CACHE_ENTRIES = 256;
const DEFAULT_CONCURRENCY = 8;

function finiteCount(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) && value >= 0
    ? value
    : undefined;
}

/** Normalize only fields whose PUM token meaning is known. */
export function knownTokensFromUsage(value: unknown): KnownSessionTokens {
  if (!value || typeof value !== "object") return {};
  const usage = value as Record<string, unknown>;
  const directOutgoing = finiteCount(usage.outgoing);
  const directIncoming = finiteCount(usage.incoming);
  const directCacheRead = finiteCount(usage.cacheRead);
  const input = finiteCount(usage.input);
  const output = finiteCount(usage.output);
  const cacheWrite = finiteCount(usage.cacheWrite);
  const legacyTokens = finiteCount(usage.tokens);

  const outgoing = directOutgoing
    ?? (input !== undefined || cacheWrite !== undefined
      ? (input ?? 0) + (cacheWrite ?? 0)
      : legacyTokens);
  const incoming = directIncoming ?? output;

  return {
    ...(outgoing !== undefined ? { outgoing } : {}),
    ...(incoming !== undefined ? { incoming } : {}),
    ...(directCacheRead !== undefined ? { cacheRead: directCacheRead } : {}),
  };
}

function addKnownTokens(total: KnownSessionTokens, value: unknown): void {
  const next = knownTokensFromUsage(value);
  if (next.outgoing !== undefined) total.outgoing = (total.outgoing ?? 0) + next.outgoing;
  if (next.incoming !== undefined) total.incoming = (total.incoming ?? 0) + next.incoming;
  if (next.cacheRead !== undefined) total.cacheRead = (total.cacheRead ?? 0) + next.cacheRead;
}

function validTimestamp(value: unknown): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value !== "string") return undefined;
  const parsed = Date.parse(value);
  return Number.isNaN(parsed) ? undefined : parsed;
}

function processLine(
  line: string,
  state: { latestUserTime?: number; tokens: KnownSessionTokens },
): void {
  if (!line.trim()) return;
  let entry: any;
  try {
    entry = JSON.parse(line);
  } catch {
    return;
  }

  if (entry?.type === "message") {
    const message = entry.message;
    if (message?.role === "user") {
      const timestamp = validTimestamp(message.timestamp) ?? validTimestamp(entry.timestamp);
      if (timestamp !== undefined) {
        state.latestUserTime = Math.max(state.latestUserTime ?? timestamp, timestamp);
      }
    }
    if (message?.role === "assistant" || message?.role === "toolResult") {
      addKnownTokens(state.tokens, message.usage);
    }
    return;
  }

  if (entry?.type === "compaction" || entry?.type === "branch_summary") {
    addKnownTokens(state.tokens, entry.usage);
  }
}

async function scanFile(path: string): Promise<Omit<SessionHistoryMetadata, "fileBytes">> {
  const state: { latestUserTime?: number; tokens: KnownSessionTokens } = { tokens: {} };
  const decoder = new StringDecoder("utf8");
  let pending = "";
  const stream = createReadStream(path);

  for await (const chunk of stream) {
    pending += decoder.write(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
    let newline = pending.indexOf("\n");
    while (newline >= 0) {
      processLine(pending.slice(0, newline), state);
      pending = pending.slice(newline + 1);
      newline = pending.indexOf("\n");
    }
  }
  pending += decoder.end();
  processLine(pending, state);

  return {
    latestUserMessageAt: state.latestUserTime === undefined
      ? null
      : new Date(state.latestUserTime),
    tokens: state.tokens,
  };
}

function statKey(size: number, mtimeMs: number): string {
  return `${size}:${mtimeMs}`;
}

async function loadFileMetadata(path: string): Promise<{ key: string; metadata: SessionHistoryMetadata }> {
  for (let attempt = 0; attempt < 2; attempt++) {
    const before = await stat(path);
    const scanned = await scanFile(path);
    const after = await stat(path);
    if (attempt === 1 || (before.size === after.size && before.mtimeMs === after.mtimeMs)) {
      return {
        key: statKey(after.size, after.mtimeMs),
        metadata: { ...scanned, fileBytes: after.size },
      };
    }
  }
  throw new Error("unreachable");
}

/**
 * Delete companion files whose session JSONL is gone. One directory read, no
 * removal on any read error, and every failure stays silent.
 */
export async function sweepOrphanedCompanions(directory: string): Promise<string[]> {
  let names: string[];
  try {
    names = await readdir(directory);
  } catch {
    return [];
  }
  const present = new Set(names);
  const removed: string[] = [];
  for (const name of names) {
    const suffix = COMPANION_SUFFIXES.find((candidate) => name.endsWith(candidate));
    if (!suffix) continue;
    if (present.has(`${name.slice(0, -suffix.length)}.jsonl`)) continue;
    try {
      await unlink(join(directory, name));
      removed.push(name);
    } catch { /* another process removed it, or it is not ours to remove */ }
  }
  return removed;
}

export function sortSessionHistory(items: readonly SessionHistoryItem[]): SessionHistoryItem[] {
  return [...items].sort((a, b) => {
    const aLatest = a.historyMetadata.latestUserMessageAt?.getTime();
    const bLatest = b.historyMetadata.latestUserMessageAt?.getTime();
    if (aLatest !== undefined || bLatest !== undefined) {
      if (aLatest === undefined) return 1;
      if (bLatest === undefined) return -1;
      if (aLatest !== bLatest) return bLatest - aLatest;
    }

    const aCreated = Number.isNaN(a.created.getTime()) ? 0 : a.created.getTime();
    const bCreated = Number.isNaN(b.created.getTime()) ? 0 : b.created.getTime();
    if (aCreated !== bCreated) return bCreated - aCreated;
    return a.path.localeCompare(b.path);
  });
}

export class SessionHistoryIndex {
  private readonly cache = new Map<string, CacheEntry>();
  private swept = false;

  constructor(
    private readonly maxCacheEntries = DEFAULT_MAX_CACHE_ENTRIES,
    private readonly concurrency = DEFAULT_CONCURRENCY,
  ) {}

  private remember(path: string, entry: CacheEntry): void {
    this.cache.delete(path);
    this.cache.set(path, entry);
    while (this.cache.size > this.maxCacheEntries) {
      const oldest = this.cache.keys().next().value;
      if (oldest === undefined) break;
      this.cache.delete(oldest);
    }
  }

  private async metadataFor(path: string): Promise<SessionHistoryMetadata> {
    try {
      const stats = await stat(path);
      const key = statKey(stats.size, stats.mtimeMs);
      const cached = this.cache.get(path);
      if (cached?.key === key) {
        this.remember(path, cached);
        return cached.metadata;
      }
      const loaded = await loadFileMetadata(path);
      this.remember(path, loaded);
      return loaded.metadata;
    } catch {
      return { latestUserMessageAt: null, fileBytes: null, tokens: {} };
    }
  }

  /** Sweep each session directory once per process, before the first listing. */
  private async sweepOnce(sessions: readonly SessionInfo[]): Promise<void> {
    if (this.swept) return;
    this.swept = true;
    const directories = new Set(sessions.map((session) => dirname(session.path)));
    for (const directory of directories) await sweepOrphanedCompanions(directory);
  }

  async load(sessions: readonly SessionInfo[]): Promise<SessionHistoryItem[]> {
    await this.sweepOnce(sessions);
    const items = new Array<SessionHistoryItem>(sessions.length);
    let next = 0;
    const worker = async () => {
      while (next < sessions.length) {
        const index = next++;
        const session = sessions[index]!;
        items[index] = {
          ...session,
          historyMetadata: await this.metadataFor(session.path),
        };
      }
    };
    await Promise.all(Array.from(
      { length: Math.min(this.concurrency, sessions.length) },
      worker,
    ));
    return sortSessionHistory(items);
  }
}

export function formatSessionBytes(bytes: number | null): string {
  if (bytes === null) return "size ?";
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KiB", "MiB", "GiB", "TiB"];
  let value = bytes / 1024;
  let unit = units[0]!;
  for (let index = 1; index < units.length && value >= 1024; index++) {
    value /= 1024;
    unit = units[index]!;
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${unit}`;
}

export function formatLatestUserTime(
  value: Date | null,
  locales?: Intl.LocalesArgument,
  options: Intl.DateTimeFormatOptions = {},
): string {
  if (!value || Number.isNaN(value.getTime())) return "no user message";
  return value.toLocaleString(locales, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
    ...options,
  });
}
